# Generated by Django 2.0 on 2018-10-24 17:45

from django.db import migrations, models
import djongo.models.fields
import labirynt_webapp.models.product


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('amount', djongo.models.fields.EmbeddedModelField(model_container=labirynt_webapp.models.product.Amount, null=True)),
                ('prices', djongo.models.fields.EmbeddedModelField(model_container=labirynt_webapp.models.product.Prices, null=True)),
                ('additional_info', djongo.models.fields.EmbeddedModelField(model_container=labirynt_webapp.models.product.AdditionalInfo, null=True)),
                ('upload_date', models.DateTimeField()),
            ],
        ),
    ]
